-- ke_toan_01_luat_seed — SINH BẰNG tools/scripts/ke_toan_sinh_luat_sql.py, KHÔNG sửa tay.
-- Cách lùi nếu hỏng: delete from accounting.rules where origin in ('override_json','rule_excel','history');
insert into accounting.rules (kind, pattern, target_code, condition, priority, origin) values
  ('supplier', 'niso', 'cp.vanhanhchung', null, 0, 'override_json'),
  ('supplier', 'am thuc viet nhat', 'cp.vanhanhchung', null, 1, 'override_json'),
  ('supplier', 'truth home', 'cp.vanhanhchung', null, 2, 'override_json'),
  ('supplier', 'eton', 'cp.thuekho', null, 3, 'override_json'),
  ('supplier', 'ky thuong', 'cp.bank', null, 4, 'override_json'),
  ('supplier', 'techcombank', 'cp.bank', null, 5, 'override_json'),
  ('supplier', 'thoi trang gmn', 'cp.phucloi', null, 6, 'override_json'),
  ('supplier', 'tsuiteru', 'cp.vanhanhchung', null, 7, 'override_json'),
  ('supplier', 'am thuc unicb', 'cp.vanhanhchung', null, 8, 'override_json'),
  ('supplier', 'infinity viet nam', 'cp.vanhanhchung', null, 9, 'override_json'),
  ('supplier', 'gelex', 'cp.vanhanhchung', null, 10, 'override_json'),
  ('supplier', 'duc nhan', 'cp.vanhanhchung', null, 11, 'override_json'),
  ('supplier', 'grand forward', 'cp.muahang', null, 12, 'override_json'),
  ('supplier', 'van tai ttl', 'cp.muahang', null, 13, 'override_json'),
  ('supplier', 'van tai anzen', 'cp.muahang', null, 14, 'override_json'),
  ('supplier', 'dich vu thuong mai 126', 'cp.muahang', null, 15, 'override_json'),
  ('supplier', 'cang container quoc te', 'cp.muahang', null, 16, 'override_json'),
  ('keyword', 'coworking', 'cp.642khac', null, 0, 'override_json'),
  ('keyword', 'co-working', 'cp.642khac', null, 1, 'override_json'),
  ('keyword', 'thu tuc hai quan', 'cp.muahang', null, 2, 'override_json'),
  ('keyword', 'nang ha cont', 'cp.muahang', null, 3, 'override_json'),
  ('keyword', 'ha vo cont', 'cp.muahang', null, 4, 'override_json'),
  ('keyword', 'phi lenh giao hang', 'cp.muahang', null, 5, 'override_json'),
  ('keyword', 'lam hang tai cang', 'cp.muahang', null, 6, 'override_json'),
  ('keyword', 'phi can bang cont', 'cp.muahang', null, 7, 'override_json'),
  ('keyword', 'phu phi nang ha', 'cp.muahang', null, 8, 'override_json'),
  ('keyword', 'giao cont hang', 'cp.muahang', null, 9, 'override_json'),
  ('keyword', 'phu thu nhien lieu', 'cp.muahang', null, 10, 'override_json'),
  ('keyword', 'cuoc van chuyen bien', 'cp.muahang', null, 11, 'override_json'),
  ('keyword', 've sinh cont', 'cp.muahang', null, 12, 'override_json'),
  ('keyword', 'van tai bo', 'cp.muahang', null, 13, 'override_json'),
  ('keyword', 'giao nhan tai xuong', 'cp.muahang', null, 14, 'override_json'),
  ('keyword', 'cic', 'cp.muahang', null, 15, 'override_json'),
  ('keyword', 'hbl', 'cp.muahang', null, 16, 'override_json'),
  ('keyword', 'file job', 'cp.muahang', null, 17, 'override_json'),
  ('keyword', 'so cont', 'cp.muahang', null, 18, 'override_json'),
  ('keyword', 'ten tau', 'cp.muahang', null, 19, 'override_json'),
  ('keyword', 'van chuyen hanh khach', 'cp.dichuyen', null, 20, 'override_json'),
  ('keyword', 've xe', 'cp.dichuyen', null, 21, 'override_json'),
  ('keyword', 'cho thue body', 'cp.qc', null, 22, 'override_json'),
  ('keyword', 'in ao', 'cp.phucloi', null, 23, 'override_json'),
  ('keyword', 'dien thoai', 'cp.642khac', null, 24, 'override_json'),
  ('keyword', 'phong nghi', 'cp.congtac', null, 25, 'override_json'),
  ('keyword', 'ao polo', 'cp.phucloi', null, 26, 'override_json'),
  ('product_name', 'may bom initial jet 3-4', 'WILOJET44', null, 0, 'override_json'),
  ('product_name', 'may bom initial jet', 'WILOJET44', null, 1, 'override_json'),
  ('product_name', 'te deu vesbo 25mm', 'T25VB', null, 2, 'override_json'),
  ('product_name', 'rac co nhua vesbo 25mm', 'RC25VB', null, 3, 'override_json'),
  ('product_name', 'rac co nhua vesbo 25mm (mau den)', 'RC25VB', null, 4, 'override_json'),
  ('product_name', 'cfnc filter for ctd50', 'LX-CFNC-002-G', null, 5, 'override_json'),
  ('product_name', 'cfnc filter (for ctd50)', 'LX-CFNC-002-G', null, 6, 'override_json'),
  ('product_name', 'loi loc cfnc bo phan cua may loc nuoc ctd50', 'LX-CFNC-002-G', null, 7, 'override_json'),
  ('product_name', 'loi loc cfnc bo phan cua may loc nuoc cts10', 'LX-CFNC-001-G', null, 8, 'override_json'),
  ('product_name', 'vo sen tam aromatheraphy ge (hong)', 'GEUS-00X06', null, 9, 'override_json'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong)', 'GEUS-00X06', null, 10, 'override_json'),
  ('product_name', 'voi sen tam aromatherapy ge (hong)', 'GEUS-00X06', null, 11, 'override_json'),
  ('product_name', 'loi loc voi sen tam the he 2', 'VOISEN-LOILOC', null, 12, 'override_json'),
  ('product_name', 'binh chua nuoc sparkling cho may ge cts10', 'GEUS-00X05', null, 13, 'override_json'),
  ('product_name', 'dich vu van chuyen', 'DVVC', null, 14, 'override_json'),
  ('product_name', 'chi phi van chuyen', 'DVVC', null, 15, 'override_json'),
  ('supplier', 'facebook ads', 'cp.qc', null, 0, 'rule_excel'),
  ('supplier', 'cong ty tnhh shopee', 'cp.shopeemall', 'Riêng «Phí dịch vụ đấu thầu từ khóa (Paid Ads)» → cp.qc', 1, 'rule_excel'),
  ('supplier', 'cong ty tnhh mtv dich vu kho van viettel', 'cp.thuekho', '«Phí vận hành kho» → cp.thuekho; «Phí/Cước chuyển phát» → DVVC', 2, 'rule_excel'),
  ('supplier', 'cong ty tnhh lalamove vietnam', 'DVVC', null, 3, 'rule_excel'),
  ('supplier', 'cong ty tnhh esheep kitchen', 'cp.qc', null, 4, 'rule_excel'),
  ('supplier', 'cong ty co phan dau tu times square viet nam', 'cp.vanhanhchung', 'Toàn bộ tiền phòng + phí phục vụ về 1 mã, không chẻ dòng', 5, 'rule_excel'),
  ('supplier', 'cong ty tnhh tu van va dao tao nextgen tax', 'cp.dvkt', null, 6, 'rule_excel'),
  ('supplier', 'cong ty tnhh nexia stt', 'cp.dvkt', null, 7, 'rule_excel'),
  ('supplier', 'ncc ca nhan 8 (che ten — nhap lai qua app)', 'cp.thuekho', 'Cả tiền thuê kho lẫn tiền điện kho', 8, 'rule_excel'),
  ('supplier', 'cong ty tnhh dich vu an uong long hung phat', 'cp.vanhanhchung', null, 9, 'rule_excel'),
  ('supplier', 'cong ty tnhh tita art', 'cp.tangbh', 'Trà + chén gốm đều là hàng tặng → cùng 1 mã', 10, 'rule_excel'),
  ('supplier', 'cong ty tnhh gia studios', 'cp.qc', 'Quần áo mua đi event — CẦN CHỐT: cp.qc hay cp.phucloi', 11, 'rule_excel'),
  ('supplier', 'cong ty tnhh dau tu tm va van tai a dong', 'DVVC', null, 12, 'rule_excel'),
  ('supplier', 'cong ty cp di chuyen xanh va thong minh gsm (xanh sm)', 'cp.dichuyen', 'Nếu điểm đi/đến là kho–nhà máy–khách hàng (chở hàng) → DVVC', 13, 'rule_excel'),
  ('supplier', 'cong ty tnhh kabinet group (tap chi art nation)', 'cp.qc', null, 14, 'rule_excel'),
  ('supplier', 'cong ty co phan be group', 'cp.dichuyen', 'Cả cước phí vận tải, phí ứng dụng Be, chiết khấu, phí khác', 15, 'rule_excel'),
  ('supplier', 'cong ty tnhh tm dich vu sa phu', 'cp.tiepkhach', 'CẦN BẢNG KÊ — 1 hoá đơn gộp 16,8tr chưa rõ nội dung', 16, 'rule_excel'),
  ('supplier', 'tong cong ty hang khong viet nam (vietnam airlines)', 'cp.congtac', 'Vé cho chuyến phát triển thị trường mới → cp.vanhanhchung', 17, 'rule_excel'),
  ('supplier', 'cong ty tnhh dich vu van tai anzen', 'DVVC', null, 18, 'rule_excel'),
  ('supplier', 'cong ty cp van chuyen va dvtm 126', 'DVVC', null, 19, 'rule_excel'),
  ('supplier', 'cong ty tnhh hang khong mat troi phu quoc (sun air)', 'cp.congtac', 'Hiện đang bị chẻ 2 mã — phải thống nhất', 20, 'rule_excel'),
  ('supplier', 'cong ty tnhh tm dich vu farmi (smartangel)', 'cp.phucloi', null, 21, 'rule_excel'),
  ('supplier', 'cong ty tnhh tm va dv thu anh', 'cp.vanhanhchung', '«liên hoan văn phòng» → cp.phucloi', 22, 'rule_excel'),
  ('supplier', 'chi nhanh ii cong ty tnhh cao boi nam my', 'cp.vanhanhchung', null, 23, 'rule_excel'),
  ('supplier', 'chi nhanh ct tnhh mtv vien thong quoc te fpt', 'cp.642khac', 'KHÔNG phải ngân hàng — không dùng cp.bank', 24, 'rule_excel'),
  ('supplier', 'ncc ca nhan 25 (che ten — nhap lai qua app)', 'cp.vanhanhchung', '«Set vỏ hộp quà», «kẹo» = quà → cp.tangbh', 25, 'rule_excel'),
  ('supplier', 'ho kinh doanh ba nhat', 'cp.vanhanhchung', null, 26, 'rule_excel'),
  ('supplier', 'cong ty tnhh ocean palace', 'cp.phucloi', 'Liên hoan văn phòng', 27, 'rule_excel'),
  ('supplier', 'cong ty tnhh an nam phuong', 'cp.vanhanhchung', null, 28, 'rule_excel'),
  ('supplier', 'cong ty tnhh pt thuong mai aki viet nam', 'cp.vanhanhchung', null, 29, 'rule_excel'),
  ('supplier', 'ngan hang tmcp ky thuong vn (techcombank)', 'cp.bank', '«Chi phí thanh toán quốc tế» → cp.ttqt', 30, 'rule_excel'),
  ('supplier', 'trung tam ky thuat tieu chuan do luong chat luong 1', 'cp.kiemdinh', null, 31, 'rule_excel'),
  ('supplier', 'trung tam dv khkt suc khoe va moi truong', 'cp.kiemdinh', null, 32, 'rule_excel'),
  ('supplier', 'cong ty tnhh lotte hotel viet nam', 'cp.vanhanhchung', null, 33, 'rule_excel'),
  ('supplier', 'cong ty co phan mvillage', 'cp.congtac', 'Thuê phòng lưu trú', 34, 'rule_excel'),
  ('supplier', 'cong ty cp dia oc ky nguyen', 'cp.vanhanhchung', 'Room Charge', 35, 'rule_excel'),
  ('supplier', 'tong cong ty cp buu chinh viettel (viettel post)', 'DVVC', null, 36, 'rule_excel'),
  ('supplier', 'tap doan cn - vien thong quan doi (viettel)', 'DVVC', null, 37, 'rule_excel'),
  ('supplier', 'cong ty cp phuc anh quoc', 'cp.dichuyen', 'Thuê xe có biển số — nếu chở hàng thì DVVC', 38, 'rule_excel'),
  ('supplier', 'cong ty tnhh chuyen phat nhanh bao an', 'DVVC', null, 39, 'rule_excel'),
  ('supplier', 'cong ty tnhh p.a viet nam', 'cp.642khac', 'Tên miền .VN — nên treo 242 phân bổ 12 tháng', 40, 'rule_excel'),
  ('supplier', 'cong ty tnhh pancake viet nam', 'cp.642khac', null, 41, 'rule_excel'),
  ('supplier', 'cong ty tnhh chuyen doi so doanh nghiep so9', 'cp.642khac', null, 42, 'rule_excel'),
  ('supplier', 'cong ty co phan tap doan hvn (google workspace)', 'cp.642khac', 'Hợp đồng 09/03-22/11/2026 — nên treo 242 phân bổ', 43, 'rule_excel'),
  ('supplier', 'cong ty tnhh tm dv xay dung xuan lanh 01', 'cp.vattukho', null, 44, 'rule_excel'),
  ('supplier', 'cong ty tnhh tm va dich vu sd', 'cp.vattukho', null, 45, 'rule_excel'),
  ('supplier', 'cong ty tnhh mtv dich vu cang xanh', 'cp.vattukho', 'Phí vệ sinh container hàng nhập — cân nhắc DVVC/giá vốn', 46, 'rule_excel'),
  ('supplier', 'cong ty tnhh sx tm dv hlc group', 'cp.vattukho', 'Xốp hơi đóng gói', 47, 'rule_excel'),
  ('supplier', 'cong ty cp bao bi dizota viet nam', 'cp.vattukho', null, 48, 'rule_excel'),
  ('supplier', 'cong ty tnhh sx va tm on ap nhat linh', 'cp.vattukho', null, 49, 'rule_excel'),
  ('supplier', 'cong ty tnhh giai tri tt artistpro', 'cp.vattukho', 'In decal + công dán bình = hoàn thiện bao bì', 50, 'rule_excel'),
  ('supplier', 'cong ty tnhh giao duc edmicro', 'cp.tangbh', 'Sách tặng kèm', 51, 'rule_excel'),
  ('supplier', 'cong ty co phan comicola', 'cp.phucloi', 'Móc khoá', 52, 'rule_excel'),
  ('supplier', 'chi nhanh ct tnhh decathlon viet nam', 'cp.phucloi', null, 53, 'rule_excel'),
  ('supplier', 'cong ty cp duoc pham fpt long chau', 'cp.phucloi', null, 54, 'rule_excel'),
  ('supplier', 'cong ty tnhh sinali', 'cp.vanhanhchung', 'Hiện T1 để cp.phucloi, T6 để cp.vanhanhchung — phải thống nhất', 55, 'rule_excel'),
  ('supplier', 'cong ty cp dien thong minh bien phuc', 'cp.freelance', 'Nhân công lắp/khảo sát máy', 56, 'rule_excel'),
  ('supplier', 'cong ty tnhh my thuat va xay dung thai son', 'cp.ccdc', 'Khung tranh — không phải tiếp khách', 57, 'rule_excel'),
  ('supplier', 'cong ty tnhh thuong mai tong hop htv', 'cp.ccdc', 'Chuột Logitech — thiết bị văn phòng', 58, 'rule_excel'),
  ('supplier', 'cong ty tnhh tmdv huyen tran phat chinh', 'cp.ccdc', 'Bàn phím Logitech — thiết bị văn phòng', 59, 'rule_excel'),
  ('supplier', 'cong ty tnhh inox tien tho', 'cp.642khac', 'Sửa tủ', 60, 'rule_excel'),
  ('supplier', 'cong ty tnhh tm xnk sieu phong', 'cp.vattukho', 'Máy bơm APP — vật tư, không phải quản lý khác', 61, 'rule_excel'),
  ('supplier', 'ngan hang tmcp ngoai thuong vn (vietcombank)', 'cp.bank', null, 62, 'rule_excel'),
  ('supplier', 'cong ty tnhh youcan', 'cp.qc', 'Thuê đầm/váy cho sản xuất nội dung', 63, 'rule_excel'),
  ('supplier', 'ho kinh doanh banh xeo rau rung pho thanh', 'cp.vanhanhchung', 'Ăn với KOL — không phải khách ra doanh số', 64, 'rule_excel'),
  ('supplier', 'cac nha hang/quan con lai (meltdown kitchen, pig makers, tan hai van, trung nhat, song dem, ngoc tu, ajigen, hong lam, khoruou, moonstone, dragoncello, hoang phuong…)', 'cp.vanhanhchung', 'Nếu tiếp khách mảng chính ra doanh số → cp.tiepkhach', 65, 'rule_excel'),
  ('keyword', 'hach toan luong thang', 'cp.luong', 'Phần thưởng Tết / lương tháng 13 / thưởng KPI nằm chung trong bút toán', 0, 'rule_excel'),
  ('keyword', 'bao hiem xa hoi tx do cty dong', 'cp.bhxh', 'Phần do người lao động đóng (TK 3341/338x)', 100, 'rule_excel'),
  ('keyword', '(tk 6421', 'cp.bhxh', 'Phần do người lao động đóng (TK 3341/338x)', 101, 'rule_excel'),
  ('keyword', '3383 3384 3386)', 'cp.bhxh', 'Phần do người lao động đóng (TK 3341/338x)', 102, 'rule_excel'),
  ('keyword', 'kinh phi cong doan tx do cty dong', 'cp.congdoan', null, 200, 'rule_excel'),
  ('keyword', '(tk 6421', 'cp.congdoan', null, 201, 'rule_excel'),
  ('keyword', '3382)', 'cp.congdoan', null, 202, 'rule_excel'),
  ('keyword', 'gwt thanh toan freelancer', 'cp.freelance', 'Người nấu cơm trưa  · Người đi lấy mẫu test nước · Người giới thiệu bán hàng (KTS)', 300, 'rule_excel'),
  ('keyword', 'gwt thanh toan thang', 'cp.freelance', 'Người nấu cơm trưa  · Người đi lấy mẫu test nước · Người giới thiệu bán hàng (KTS)', 301, 'rule_excel'),
  ('keyword', 'nhan cong lap khao sat may', 'cp.freelance', 'Người nấu cơm trưa  · Người đi lấy mẫu test nước · Người giới thiệu bán hàng (KTS)', 302, 'rule_excel'),
  ('keyword', 'hach toan thue tncn freelance', 'cp.freelance', 'Người nấu cơm trưa  · Người đi lấy mẫu test nước · Người giới thiệu bán hàng (KTS)', 303, 'rule_excel'),
  ('keyword', 'gwt thanh toan kts', 'cp.hoahong', 'KTS được thuê làm kỹ thuật lắp đặt', 400, 'rule_excel'),
  ('keyword', 'gioi thieu ban hang', 'cp.hoahong', 'KTS được thuê làm kỹ thuật lắp đặt', 401, 'rule_excel'),
  ('keyword', 'bo 30a', 'cp.hoahong', 'KTS được thuê làm kỹ thuật lắp đặt', 402, 'rule_excel'),
  ('keyword', '(ten bo san pham khach mua)', 'cp.hoahong', 'KTS được thuê làm kỹ thuật lắp đặt', 403, 'rule_excel'),
  ('keyword', 'nau com trua', 'cp.phucloi', 'Ăn uống có khách bên ngoài', 500, 'rule_excel'),
  ('keyword', 'lien hoan van phong', 'cp.phucloi', 'Ăn uống có khách bên ngoài', 501, 'rule_excel'),
  ('keyword', 'chi phi phuc loi cho nhan vien', 'cp.phucloi', 'Ăn uống có khách bên ngoài', 502, 'rule_excel'),
  ('keyword', 'do dung ca nhan', 'cp.phucloi', 'Ăn uống có khách bên ngoài', 503, 'rule_excel'),
  ('keyword', 'gia dinh nhan vien (smartangel men vi sinh sach ve su kien)', 'cp.phucloi', 'Ăn uống có khách bên ngoài', 504, 'rule_excel'),
  ('keyword', 'an uong', 'cp.tiepkhach', 'Khách thuộc thị trường/sản phẩm MỚI đang thăm dò · nội bộ nhân viên · hàng tặng kèm máy', 600, 'rule_excel'),
  ('keyword', 'qua cho khach hang dang mua hoac sap mua may loc nuoc', 'cp.tiepkhach', 'Khách thuộc thị trường/sản phẩm MỚI đang thăm dò · nội bộ nhân viên · hàng tặng kèm máy', 601, 'rule_excel'),
  ('keyword', 'chi phi van hanh chung (kps)', 'cp.vanhanhchung', 'Đồ dùng văn phòng, nước uống, thiết bị cho nhân viên dùng hằng ngày', 700, 'rule_excel'),
  ('keyword', 'hoa don nha hang', 'cp.vanhanhchung', 'Đồ dùng văn phòng, nước uống, thiết bị cho nhân viên dùng hằng ngày', 701, 'rule_excel'),
  ('keyword', 'khach san', 'cp.vanhanhchung', 'Đồ dùng văn phòng, nước uống, thiết bị cho nhân viên dùng hằng ngày', 702, 'rule_excel'),
  ('keyword', 'quan ma muc dich la gap doi tac thi truong moi', 'cp.vanhanhchung', 'Đồ dùng văn phòng, nước uống, thiết bị cho nhân viên dùng hằng ngày', 703, 'rule_excel'),
  ('keyword', 'san pham mua ve test', 'cp.vanhanhchung', 'Đồ dùng văn phòng, nước uống, thiết bị cho nhân viên dùng hằng ngày', 704, 'rule_excel'),
  ('keyword', 'tang kem khi ban may', 'cp.tangbh', 'Quà biếu đối tác không gắn với đơn hàng', 800, 'rule_excel'),
  ('keyword', 'tra qua bieu sach co ghi chu', 'cp.tangbh', 'Quà biếu đối tác không gắn với đơn hàng', 801, 'rule_excel'),
  ('keyword', 'thanh toan fb ads', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1000, 'rule_excel'),
  ('keyword', 'seller value-added services svs', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1001, 'rule_excel'),
  ('keyword', 'phi dich vu dau thau tu khoa (svs - paid ads)', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1002, 'rule_excel'),
  ('keyword', 'phi dich vu hien thi (svs - display service)', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1003, 'rule_excel'),
  ('keyword', 'phi dich vu tiep thi lien ket pps', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1004, 'rule_excel'),
  ('keyword', 'chi phi quang cao', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1005, 'rule_excel'),
  ('keyword', 'moi dong shopee co chu — gom va', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1006, 'rule_excel'),
  ('keyword', 'booking kol', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1007, 'rule_excel'),
  ('keyword', 'bao chi', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1008, 'rule_excel'),
  ('keyword', 'tap chi', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1009, 'rule_excel'),
  ('keyword', 'thue trang phuc san xuat noi dung', 'cp.qc', 'Phí sàn thuần tuý: hoa hồng cố định, xử lý giao dịch, PiShip, rút tiền, phí dịch vụ (Service Fee), AMS', 1010, 'rule_excel'),
  ('keyword', 'phi hoa hong co dinh (commission fee)', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1100, 'rule_excel'),
  ('keyword', 'phi xu ly giao dich (transaction fee)', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1101, 'rule_excel'),
  ('keyword', 'phi dich vu 2026 (service fee)', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1102, 'rule_excel'),
  ('keyword', 'phi dich vu piship', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1103, 'rule_excel'),
  ('keyword', 'phi rut tien (withdrawal fee)', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1104, 'rule_excel'),
  ('keyword', 'phi dich vu tmdt ams', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1105, 'rule_excel'),
  ('keyword', 'phi dich vu phat sinh tung lan tren shopee mall', 'cp.shopeemall', 'Mọi dòng có «Seller Value-Added Services / SVS» (Paid Ads, Display service) và «PPS tiếp thị liên kết» = quảng cáo, KHÔNG phải phí sàn', 1106, 'rule_excel'),
  ('keyword', 'hop dong', 'cp.kol', 'Tiền ăn uống khi gặp KOL', 1200, 'rule_excel'),
  ('keyword', 'thanh toan cho kol koc', 'cp.kol', 'Tiền ăn uống khi gặp KOL', 1201, 'rule_excel'),
  ('keyword', 'cuoc chuyen phat', 'DVVC', 'Cước chở NGƯỜI · phí vận hành kho', 1300, 'rule_excel'),
  ('keyword', 'cuoc van chuyen hang', 'DVVC', 'Cước chở NGƯỜI · phí vận hành kho', 1301, 'rule_excel'),
  ('keyword', 'phi chuyen phat theo bang ke', 'DVVC', 'Cước chở NGƯỜI · phí vận hành kho', 1302, 'rule_excel'),
  ('keyword', 'phi ve sinh container hang nhap', 'DVVC', 'Cước chở NGƯỜI · phí vận hành kho', 1303, 'rule_excel'),
  ('keyword', 'cuoc van chuyen khach hanh khach', 'cp.dichuyen', 'Điểm đến là kho/nhà máy/khách hàng để giao nhận hàng · vé máy bay đi công tác', 1400, 'rule_excel'),
  ('keyword', 'be group (cuoc phi van tai + phi ung dung be + chiet khau)', 'cp.dichuyen', 'Điểm đến là kho/nhà máy/khách hàng để giao nhận hàng · vé máy bay đi công tác', 1401, 'rule_excel'),
  ('keyword', 'xanh sm', 'cp.dichuyen', 'Điểm đến là kho/nhà máy/khách hàng để giao nhận hàng · vé máy bay đi công tác', 1402, 'rule_excel'),
  ('keyword', 'diem den la van phong khach san nha hang nha rieng', 'cp.dichuyen', 'Điểm đến là kho/nhà máy/khách hàng để giao nhận hàng · vé máy bay đi công tác', 1403, 'rule_excel'),
  ('keyword', 'chi phi ve may bay', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1500, 'rule_excel'),
  ('keyword', 'chi phi cong tac', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1501, 'rule_excel'),
  ('keyword', 'dich vu phong room charge', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1502, 'rule_excel'),
  ('keyword', 'dich vu thue phong', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1503, 'rule_excel'),
  ('keyword', 'phi dich vu cho thue phong nghi', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1504, 'rule_excel'),
  ('keyword', 'ma dat cho hang khong (vd 96dmxu', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1505, 'rule_excel'),
  ('keyword', '8092 )', 'cp.congtac', 'Chuyến đi phục vụ phát triển thị trường mới (theo định nghĩa cp.vanhanhchung)', 1506, 'rule_excel'),
  ('keyword', 'phi van hanh kho thang theo bang ke vkvmb0643 vkvmb0631 vkvmb0629', 'cp.thuekho', '«Phí chuyển phát theo bảng kê VKVMB…» — cùng nhà cung cấp Viettel Post nhưng khác bản chất', 1600, 'rule_excel'),
  ('keyword', 'phi thue kho nguyen xien', 'cp.thuekho', '«Phí chuyển phát theo bảng kê VKVMB…» — cùng nhà cung cấp Viettel Post nhưng khác bản chất', 1601, 'rule_excel'),
  ('keyword', 'trich truoc chi phi thue kho thang x', 'cp.thuekho', '«Phí chuyển phát theo bảng kê VKVMB…» — cùng nhà cung cấp Viettel Post nhưng khác bản chất', 1602, 'rule_excel'),
  ('keyword', 'tien dien kho', 'cp.thuekho', '«Phí chuyển phát theo bảng kê VKVMB…» — cùng nhà cung cấp Viettel Post nhưng khác bản chất', 1603, 'rule_excel'),
  ('keyword', 'dich vu ghi so ke toan', 'cp.dvkt', null, 1700, 'rule_excel'),
  ('keyword', 'dich vu tinh luong va tuan thu', 'cp.dvkt', null, 1701, 'rule_excel'),
  ('keyword', 'chi phi ra soat nexgentax', 'cp.dvkt', null, 1702, 'rule_excel'),
  ('keyword', 'dich vu ke toan', 'cp.dvkt', null, 1703, 'rule_excel'),
  ('keyword', 'kinh phi xet nghiem nuoc', 'cp.kiemdinh', null, 1800, 'rule_excel'),
  ('keyword', 'chi phi kiem dinh', 'cp.kiemdinh', null, 1801, 'rule_excel'),
  ('keyword', 'lay mau test nuoc', 'cp.kiemdinh', null, 1802, 'rule_excel'),
  ('keyword', 'ten chi tieu vi sinh (coliforms pseudomonas aeruginosa streptococci feacal bao tu vi khuan ky khi)', 'cp.kiemdinh', null, 1803, 'rule_excel'),
  ('keyword', 'do dung vat tu cho kho', 'cp.vattukho', null, 1900, 'rule_excel'),
  ('keyword', 'loi loc coc loc van ong nuoc bang keo may bom bien ap xop hoi in decal cong dan bao bi san pham', 'cp.vattukho', null, 1901, 'rule_excel'),
  ('keyword', 'phan bo chi phi ccdc thang x', 'cp.ccdc', null, 2000, 'rule_excel'),
  ('keyword', 'phan bo chi phi tra truoc thang x', 'cp.ccdc', null, 2001, 'rule_excel'),
  ('keyword', 'thiet bi van phong don le (chuot ban phim tranh)', 'cp.ccdc', null, 2002, 'rule_excel'),
  ('keyword', 'phi duy tri ten mien .vn', 'cp.642khac', 'Chỉ dùng khi KHÔNG khớp mã nào ở trên — mã này phải giữ ở mức nhỏ', 2100, 'rule_excel'),
  ('keyword', 'pancake so9 google workspace fpt (oncall', 'cp.642khac', 'Chỉ dùng khi KHÔNG khớp mã nào ở trên — mã này phải giữ ở mức nhỏ', 2101, 'rule_excel'),
  ('keyword', 'internet) sua chua nho van phong', 'cp.642khac', 'Chỉ dùng khi KHÔNG khớp mã nào ở trên — mã này phải giữ ở mức nhỏ', 2102, 'rule_excel'),
  ('keyword', 'phi ngan hang', 'cp.bank', 'Phí thanh toán quốc tế · nhà cung cấp không phải ngân hàng (VD FPT)', 2200, 'rule_excel'),
  ('keyword', 'thu phi qltk to chuc-vnd', 'cp.bank', 'Phí thanh toán quốc tế · nhà cung cấp không phải ngân hàng (VD FPT)', 2201, 'rule_excel'),
  ('keyword', 'thu phi in sao ke tk', 'cp.bank', 'Phí thanh toán quốc tế · nhà cung cấp không phải ngân hàng (VD FPT)', 2202, 'rule_excel'),
  ('keyword', 'chi khi doi tuong la ngan hang', 'cp.bank', 'Phí thanh toán quốc tế · nhà cung cấp không phải ngân hàng (VD FPT)', 2203, 'rule_excel'),
  ('keyword', 'chi phi thanh toan quoc te', 'cp.ttqt', null, 2300, 'rule_excel'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 1', 'CTS20NG', null, 0, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 1', 'CTD50NG', null, 1, 'history'),
  ('product_name', 'may loc nuoc ge gn610 theo hoa đon so 1', 'GPUN-4000XEN-G', null, 2, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 2', 'MUOIAD', null, 3, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 3', 'WH30A', null, 4, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 3', 'GPUN-4000XEN-G', null, 5, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 4', 'CTD50NG', null, 6, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 5', 'WH30A', null, 7, 'history'),
  ('product_name', 'tu bao che thiet bi ngoai troi theo hoa đon so 5', 'TUBAOCHE', null, 8, 'history'),
  ('product_name', 'bo loc ge pcf gn610 theo hoa đon so 6', 'GT-PCF10-F02G', null, 9, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 7', 'CTD50NG', null, 10, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810 theo hoa đon so 10', 'GTUN-8500XDS-G', null, 11, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 9', 'VOISEN-LOILOC', null, 12, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 11', 'VOISEN-LOILOC', null, 13, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 12', 'GEUS-00X06', null, 14, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 13', 'GEUS-00X06', null, 15, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 13', 'VOISEN-LOILOC', null, 16, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 14', 'GEUS-00X06', null, 17, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 15', 'GEUS-00X06', null, 18, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 16', 'GEUS-00X06', null, 19, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 17', 'CTS20NG', null, 20, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 18', 'CTD50NG', null, 21, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 19', 'CTD50NG', null, 22, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 20', 'GEUS-00X06', null, 23, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 20', 'VOISEN-LOILOC', null, 24, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 21', 'VOISEN-LOILOC', null, 25, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 22', 'GEUS-00X06', null, 26, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 23', 'GEUS-00X06', null, 27, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 24', 'GEUS-00X06', null, 28, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 25', 'GEUS-00X06', null, 29, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 26', 'GEUS-00X06', null, 30, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 27', 'GEUS-00X06', null, 31, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 27', 'VOISEN-LOILOC', null, 32, 'history'),
  ('product_name', 'loi thom voi sen tam the he 2 theo hoa đon so 27', 'VOISEN-LOITHOM', null, 33, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 28', 'VOISEN-LOILOC', null, 34, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 29', 'GEUS-00X06', null, 35, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 30', 'GEUS-00X06', null, 36, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 31', 'GEUS-00X06', null, 37, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 32', 'GEUS-00X06', null, 38, 'history'),
  ('product_name', 'bo loc ge pcf gn610 theo hoa đon so 33', 'GT-PCF10-F02G', null, 39, 'history'),
  ('product_name', 'bo loc ge nf gn610 theo hoa đon so 33', 'GPUN-4000XEN-G', null, 40, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 34', 'CTS20NG', null, 41, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 34', 'GEUS-00X06', null, 42, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 35', 'CTS20NG', null, 43, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 35', 'GEUS-00X06', null, 44, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 36', 'CTD50NG', null, 45, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 37', 'CTD50NG', null, 46, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 37', 'GEUS-00X06', null, 47, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 38', 'CTS20NG', null, 48, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 38', 'GEUS-00X06', null, 49, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 39', 'CTD50NG', null, 50, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 39', 'GEUS-00X06', null, 51, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 40', 'LX-CFNC-001-G', null, 52, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 41', 'CTS20NG', null, 53, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 41', 'GEUS-00X06', null, 54, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 42', 'CTD50NG', null, 55, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a theo hoa đon so 43', 'WH15A', null, 56, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 43', 'CTD50NG', null, 57, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 44', 'MUOIAD', null, 58, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 45', 'MUOIAD', null, 59, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 46', 'WH30A', null, 60, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 46', 'CTS20NG', null, 61, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 46', 'PKONG', null, 62, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (đen) theo hoa đon so 47', 'CTS10NB', null, 63, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 48', 'GPUN-4000XEN-G', null, 64, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 49', 'CTS20NG', null, 65, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 49', 'GEUS-00X06', null, 66, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 50', 'CTD50NG', null, 67, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 50', 'GEUS-00X06', null, 68, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 51', 'CTD50NG', null, 69, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 51', 'GEUS-00X06', null, 70, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 52', 'CTS20NG', null, 71, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 52', 'GEUS-00X06', null, 72, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 53', 'CTD50NG', null, 73, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 53', 'GEUS-00X06', null, 74, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810 theo hoa đon so 54', 'GTUN-8500XDS-G', null, 75, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810 theo hoa đon so 55', 'GTUN-8500XDS-G', null, 76, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 56', 'CTS20NG', null, 77, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 56', 'GEUS-00X06', null, 78, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 57', 'CTD50NG', null, 79, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 57', 'GEUS-00X06', null, 80, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 58', 'CTD50NG', null, 81, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 58', 'GEUS-00X06', null, 82, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 59', 'CTD50NG', null, 83, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 59', 'GEUS-00X06', null, 84, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 60', 'CTS20NG', null, 85, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 60', 'GEUS-00X06', null, 86, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 61', 'CTS20NG', null, 87, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 61', 'GEUS-00X06', null, 88, 'history'),
  ('product_name', 'bo loc ge pcf gn620 theo hoa đon so 62', 'GT-PCF13-F01G', null, 89, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 63', 'MUOIAD', null, 90, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a theo hoa đon so 64', 'WH15A', null, 91, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 64', 'PKONG', null, 92, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 65', 'MUOIAD', null, 93, 'history'),
  ('product_name', 'he thong loc nuoc wh15a eco theo hoa đon so 66', 'WH15AECO', null, 94, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 67', 'MUOIAD', null, 95, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a eco theo hoa đon so 68', 'WH30AECO', null, 96, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 68', 'PKONG', null, 97, 'history'),
  ('product_name', 'chan đe ge 15a theo hoa đon so 68', 'CHANDE15A', null, 98, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 69', 'MUOIAD', null, 99, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 70', 'WH30A', null, 100, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 70', 'PKONG', null, 101, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 70', 'GPUN-4000XEN-G', null, 102, 'history'),
  ('product_name', 'bo loc ge pcf gn620 theo hoa đon so 71', 'GT-PCF13-F01G', null, 103, 'history'),
  ('product_name', 'bo loc ge pcff dn810 theo hoa đon so 72', 'LX-PPF-003-G', null, 104, 'history'),
  ('product_name', 'bo loc ge pcfb dn810 theo hoa đon so 72', 'LX-PCFB-002-G', null, 105, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 73', 'MUOIAD', null, 106, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a theo hoa đon so 74', 'WH15A', null, 107, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 74', 'PKONG', null, 108, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 74', 'CTS20NG', null, 109, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 75', 'GPUN-4000XEN-G', null, 110, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 75', 'CTS20NG', null, 111, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 76', 'GPUN-4000XEN-G', null, 112, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 77', 'MUOIAD', null, 113, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a theo hoa đon so 78', 'WH15A', null, 114, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 78', 'PKONG', null, 115, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 78', 'CTS20NG', null, 116, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (đen) theo hoa đon so 79', 'CTS10NB', null, 117, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 81', 'WH30A', null, 118, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 81', 'PKONG', null, 119, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 82', 'CTD50NG', null, 120, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 83', 'GEUS-00X06', null, 121, 'history'),
  ('product_name', 'bo loc ge pcf gn610 theo hoa đon so 84', 'GT-PCF10-F02G', null, 122, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 85', 'VOISEN-LOILOC', null, 123, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 86', 'CTD50NG', null, 124, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 87', 'CTD50NG', null, 125, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 88', 'GPUN-4000XEN-G', null, 126, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 89', 'CTD50NG', null, 127, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 90', 'VOISEN-LOILOC', null, 128, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 90', 'GEUS-00X06', null, 129, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 91', 'CTD50NG', null, 130, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 92', 'CTS20NG', null, 131, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 93', 'CTD50NG', null, 132, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 94', 'CTD50NG', null, 133, 'history'),
  ('product_name', 'bo loc ge nf gn620 theo hoa đon so 95', 'GTUN-5800EN-G', null, 134, 'history'),
  ('product_name', 'bo loc ge pcf gn620 theo hoa đon so 95', 'GT-PCF13-F01G', null, 135, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 96', 'VOISEN-LOILOC', null, 136, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 97', 'GEUS-00X06', null, 137, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 100', 'GT-PCF10-G01-G', null, 138, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 101', 'GT-PCF10-G01-G', null, 139, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 98', 'LX-CFNC-001-G', null, 140, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 99', 'CTS20NG', null, 141, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 102', 'CTD50NG', null, 142, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 102', 'GEUS-00X06', null, 143, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 103', 'CTS20NG', null, 144, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 104', 'GT-PCF10-G01-G', null, 145, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 105', 'GT-PCF10-G01-G', null, 146, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 106', 'GT-PCF10-G01-G', null, 147, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 107', 'LX-CFNC-001-G', null, 148, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 108', 'GT-PCF10-G01-G', null, 149, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 109', 'GT-PCF10-G01-G', null, 150, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 110', 'GPUN-4000XEN-G', null, 151, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 111', 'CTS20NG', null, 152, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 111', 'GEUS-00X06', null, 153, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 112', 'MUOIAD', null, 154, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 113', 'WH30A', null, 155, 'history'),
  ('product_name', 'tu bao che 30a theo hoa đon so 113', 'TUBAOCHE', null, 156, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 113', 'PKONG', null, 157, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 113', 'GPUN-4000XEN-G', null, 158, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 114', 'MUOIAD', null, 159, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a eco theo hoa đon so 115', 'WH15AECO', null, 160, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 115', 'PKONG', null, 161, 'history'),
  ('product_name', 'may loc nuoc ge ush10 theo hoa đon so 115', 'GTUN-8600HP-G', null, 162, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 116', 'MUOIAD', null, 163, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a theo hoa đon so 117', 'WH15A', null, 164, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 117', 'CTS20NG', null, 165, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 117', 'PKONG', null, 166, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620 theo hoa đon so 118', 'GTUN-5800EN-G', null, 167, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 119', 'GPUN-4000XEN-G', null, 168, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 120', 'CTD50NG', null, 169, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 120', 'GEUS-00X06', null, 170, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 121', 'CTD50NG', null, 171, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 121', 'GEUS-00X06', null, 172, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 122', 'CTS20NG', null, 173, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 122', 'GEUS-00X06', null, 174, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620 theo hoa đon so 123', 'GTUN-5800EN-G', null, 175, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 124', 'CTD50NG', null, 176, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 124', 'GEUS-00X06', null, 177, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 125', 'GPUN-4000XEN-G', null, 178, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 126', 'CTD50NG', null, 179, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 126', 'GEUS-00X06', null, 180, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 127', 'CTD50NG', null, 181, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 127', 'GEUS-00X06', null, 182, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 128', 'CTD50NG', null, 183, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 128', 'GEUS-00X06', null, 184, 'history'),
  ('product_name', 'may loc nuoc ge ush10 theo hoa đon so 129', 'GTUN-8600HP-G', null, 185, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 130', 'GT-PCF10-G01-G', null, 186, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810 theo hoa đon so 131', 'GTUN-8500XDS-G', null, 187, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 132', 'CTS20NG', null, 188, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (trang) theo hoa đon so 132', 'CTS10NW', null, 189, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 132', 'GEUS-00X06', null, 190, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 133', 'LX-CFNC-001-G', null, 191, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 134', 'CTS20NG', null, 192, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 134', 'GEUS-00X06', null, 193, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 135', 'CTD50NG', null, 194, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 135', 'GEUS-00X06', null, 195, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 136', 'CTD50NG', null, 196, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 136', 'GEUS-00X06', null, 197, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 137', 'CTS20NG', null, 198, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (đen) theo hoa đon so 137', 'CTS10NB', null, 199, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 137', 'GEUS-00X06', null, 200, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810 theo hoa đon so 138', 'GTUN-8500XDS-G', null, 201, 'history'),
  ('product_name', 'may loc nuoc ge cts2o theo hoa đon so 139', 'CTS20NG', null, 202, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 139', 'CTD50NG', null, 203, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 139', 'GEUS-00X06', null, 204, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 140', 'CTD50NG', null, 205, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 140', 'GEUS-00X06', null, 206, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 141', 'CTS20NG', null, 207, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (đen) theo hoa đon so 141', 'CTS10NB', null, 208, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 141', 'GEUS-00X06', null, 209, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 142', 'CTD50NG', null, 210, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 142', 'GEUS-00X06', null, 211, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 143', 'GT-PCF10-G01-G', null, 212, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 144', 'GPUN-4000XEN-G', null, 213, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 145', 'GT-PCF10-G01-G', null, 214, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 146', 'CTD50NG', null, 215, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 147', 'GT-PCF10-G01-G', null, 216, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 148', 'LX-CFNC-001-G', null, 217, 'history'),
  ('product_name', 'bo loc ge nf b04 theo hoa đon so 149', 'GT-NF50-G01G', null, 218, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 150', 'CTD50NG', null, 219, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 150', 'GEUS-00X06', null, 220, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 151', 'GT-PCF10-G01-G', null, 221, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 152', 'GPUN-4000XEN-G', null, 222, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 153', 'GEUS-00X06', null, 223, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 154', 'CTD50NG', null, 224, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 154', 'GEUS-00X06', null, 225, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 155', 'GEUS-00X06', null, 226, 'history'),
  ('product_name', 'loi thom voi sen tam the he 2 theo hoa đon so 155', 'VOISEN-LOITHOM', null, 227, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2 theo hoa đon so 155', 'VOISEN-LOILOC', null, 228, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 156', 'GEUS-00X06', null, 229, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 157', 'MUOIAD', null, 230, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a eco theo hoa đon so 158', 'WH30AECO', null, 231, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 158', 'PKONG', null, 232, 'history'),
  ('product_name', 'tu bao che 30a eco theo hoa đon so 158', 'TUBAOCHE', null, 233, 'history'),
  ('product_name', 'loi loc pp (danh cho upf10) theo hoa đon so 158', 'LX-PP-003-G', null, 234, 'history'),
  ('product_name', 'loi loc pac (danh cho upf10) theo hoa đon so 158', 'LX-PAC-001-G', null, 235, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 159', 'GEUS-00X06', null, 236, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 160', 'CTD50NG', null, 237, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 160', 'GEUS-00X06', null, 238, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 161', 'CTD50NG', null, 239, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 161', 'GEUS-00X06', null, 240, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 162', 'GEUS-00X06', null, 241, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620 theo hoa đon so 163', 'GTUN-5800EN-G', null, 242, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620 theo hoa đon so 164', 'GTUN-5800EN-G', null, 243, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 165', 'GEUS-00X06', null, 244, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 166', 'GEUS-00X06', null, 245, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 167', 'GT-PCF10-G01-G', null, 246, 'history'),
  ('product_name', 'bo loc ge nf b04 theo hoa đon so 167', 'GT-NF50-G01G', null, 247, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 168', 'CTD50NG', null, 248, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 168', 'GEUS-00X06', null, 249, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 169', 'GT-PCF10-G01-G', null, 250, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 170', 'CTD50NG', null, 251, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 170', 'GEUS-00X06', null, 252, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 171', 'CTS20NG', null, 253, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 171', 'GEUS-00X06', null, 254, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 172', 'CTS20NG', null, 255, 'history'),
  ('product_name', 'bo loc ge pcf gn620 theo hoa đon so 173', 'GT-PCF13-F01G', null, 256, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 174', 'CTD50NG', null, 257, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 174', 'GEUS-00X06', null, 258, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 175', 'CTD50NG', null, 259, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 176', 'CTD50NG', null, 260, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 176', 'GEUS-00X06', null, 261, 'history'),
  ('product_name', 'bo loc ge pcf gn610 theo hoa đon so 177', 'GT-PCF10-F02G', null, 262, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (trang) theo hoa đon so 178', 'CTS10NW', null, 263, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 179', 'CTD50NG', null, 264, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 179', 'GEUS-00X06', null, 265, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 180', 'LX-CFNC-001-G', null, 266, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 181', 'CTD50NG', null, 267, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (đen) theo hoa đon so 182', 'CTS10NB', null, 268, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 183', 'GT-PCF10-G01-G', null, 269, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 184', 'CTD50NG', null, 270, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 184', 'GEUS-00X06', null, 271, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 185', 'GT-PCF10-G01-G', null, 272, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 186', 'LX-CFNC-001-G', null, 273, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 187', 'GT-PCF10-G01-G', null, 274, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 188', 'GT-PCF10-G01-G', null, 275, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 (hang trung bay) theo hoa đon so 189', 'CTD50NG', null, 276, 'history'),
  ('product_name', 'vo thiet bi loc trung tam 30a theo hoa đon so 189', 'GTEF-30A01-G-SHELL', null, 277, 'history'),
  ('product_name', 'vo thiet bi lam mem 30a theo hoa đon so 189', 'GTEC-30A01-G-SHELL', null, 278, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 190', 'CTS20NG', null, 279, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 191', 'LX-CFNC-001-G', null, 280, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 191', 'CTS20NG', null, 281, 'history'),
  ('product_name', 'bo loc ge pcff dn810 theo hoa đon so 191', 'LX-PPF-003-G', null, 282, 'history'),
  ('product_name', 'bo loc ge pcfb dn810 theo hoa đon so 192', 'LX-PCFB-002-G', null, 283, 'history'),
  ('product_name', 'bo loc ge pcff dn810 theo hoa đon so 192', 'LX-PPF-003-G', null, 284, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 192', 'LX-CFNC-001-G', null, 285, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 192', 'GT-PCF10-G01-G', null, 286, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 192', 'CTD50NG', null, 287, 'history'),
  ('product_name', 'bo loc ge nf b04 theo hoa đon so 192', 'GT-NF50-G01G', null, 288, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 193', 'CTD50NG', null, 289, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 193', 'GEUS-00X06', null, 290, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 194', 'MUOIAD', null, 291, 'history'),
  ('product_name', 'loi loc ge pcf (gpun-4000xen-g) theo hoa đon so 195', 'GT-PCF10-F02G', null, 292, 'history'),
  ('product_name', 'bo loc ge nf gn610 theo hoa đon so 195', 'GPUN-4000XEN-G', null, 293, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 196', 'CTD50NG', null, 294, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 196', 'GEUS-00X06', null, 295, 'history'),
  ('product_name', 'loi loc ge pcf (gpun-4000xen-g) theo hoa đon so 197', 'GT-PCF10-F02G', null, 296, 'history'),
  ('product_name', 'dich vu sua chua lap đat may loc nuoc theo hoa đon so 197', 'DVSC', null, 297, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 198', 'GEUS-00X06', null, 298, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 198', 'CTS20NG', null, 299, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 199', 'MUOIAD', null, 300, 'history'),
  ('product_name', 'chi phi van chuyen theo hoa đon so 199', 'DVVC', null, 301, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 200', 'MUOIAD', null, 302, 'history'),
  ('product_name', 'chi phi van chuyen theo hoa đon so 201', 'DVVC', null, 303, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 202', 'MUOIAD', null, 304, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 203', 'GEUS-00X06', null, 305, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 203', 'CTS20NG', null, 306, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 204', 'CTD50NG', null, 307, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 204', 'GEUS-00X06', null, 308, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 205', 'CTD50NG', null, 309, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 205', 'GEUS-00X06', null, 310, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 206', 'CTD50NG', null, 311, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 206', 'GEUS-00X06', null, 312, 'history'),
  ('product_name', 'bo loc ge cpf b04 theo hoa đon so 207', 'GT-PCF10-G01-G', null, 313, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 208', 'CTD50NG', null, 314, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 208', 'GEUS-00X06', null, 315, 'history'),
  ('product_name', 'bo loi loc ge cpf b04 theo hoa đon so 209', 'GT-PCF10-G01-G', null, 316, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a theo hoa đon so 210', 'WH30A', null, 317, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 210', 'PKONG', null, 318, 'history'),
  ('product_name', 'tu bao che 30a theo hoa đon so 210', 'TUBAOCHE', null, 319, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 210', 'CTD50NG', null, 320, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo theo hoa đon so 211', 'MUOIAD', null, 321, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a theo hoa đon so 212', 'WH15A', null, 322, 'history'),
  ('product_name', 'phu kien đuong ong tinh them theo hoa đon so 212', 'PKONG', null, 323, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620 theo hoa đon so 212', 'GTUN-5800EN-G', null, 324, 'history'),
  ('product_name', 'muoi (natriclorua) tinh 99.9%, dang vien, nsx: đuc theo hoa đon so 213', 'MUOIAD', null, 325, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 214', 'GEUS-00X06', null, 326, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 214', 'CTS20NG', null, 327, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620 theo hoa đon so 215', 'GTUN-5800EN-G', null, 328, 'history'),
  ('product_name', 'bo loc ge nf gn610 theo hoa đon so 216', 'GPUN-4000XEN-G', null, 329, 'history'),
  ('product_name', 'bo loc ge pcf gn620 theo hoa đon so 217', 'GT-PCF13-F01G', null, 330, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810 theo hoa đon so 217', 'GTUN-8500XDS-G', null, 331, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 217', 'GPUN-4000XEN-G', null, 332, 'history'),
  ('product_name', 'dich vu sua chua lap đat may loc nuoc theo hoa đon so 217', 'DVSC', null, 333, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 218', 'GEUS-00X06', null, 334, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 218', 'CTS20NG', null, 335, 'history'),
  ('product_name', 'bo loc ge pcf gn620 theo hoa đon so 219', 'GT-PCF13-F01G', null, 336, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 220', 'GEUS-00X06', null, 337, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 220', 'CTD50NG', null, 338, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong) theo hoa đon so 221', 'GEUS-00X06', null, 339, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 theo hoa đon so 221', 'CTD50NG', null, 340, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 222', 'GPUN-4000XEN-G', null, 341, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 223', 'GPUN-4000XEN-G', null, 342, 'history'),
  ('product_name', 'may loc nuoc ge b04 (khong loi pcf)', 'GEUT-B04-G-NF', null, 343, 'history'),
  ('product_name', 'may loc nuoc gects20 theo hoa đon so 225', 'CTS20NG', null, 344, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 225', 'GPUN-4000XEN-G', null, 345, 'history'),
  ('product_name', 'dich vu van chuyen theo hoa đon so 225', 'DVVC', null, 346, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 theo hoa đon so 226', 'GPUN-4000XEN-G', null, 347, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 226', 'CTS20NG', null, 348, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 (hang tang khong thu tien) theo hoa đon so 227', 'GPUN-4000XEN-G', null, 349, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 227', 'CTS20NG', null, 350, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 (hang tang khong thu tien) theo hoa đon so 228', 'GPUN-4000XEN-G', null, 351, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 228', 'CTS20NG', null, 352, 'history'),
  ('product_name', 'bo loc ge pcf may gn620 theo hoa đon so 229', 'GT-PCF13-F01G', null, 353, 'history'),
  ('product_name', 'may loc nuoc ge cts20 theo hoa đon so 229', 'CTS20NG', null, 354, 'history'),
  ('product_name', 'bo loc ge cfnc cts10 theo hoa đon so 229', 'LX-CFNC-001-G', null, 355, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (trang) theo hoa đon so 229', 'CTS10NW', null, 356, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft', 'MUOIAD', null, 357, 'history'),
  ('product_name', 'may loc nuoc ge ctd50', 'CTD50NG', null, 358, 'history'),
  ('product_name', 'may loc nuoc ge cts20', 'CTS20NG', null, 359, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (hong)', 'GEUS-00X06', null, 360, 'history'),
  ('product_name', 'bo loc sach voi sen tam the he 2', 'VOISEN-LOILOC', null, 361, 'history'),
  ('product_name', 'bo loc ge cfnc cho may cts10', 'LX-CFNC-001-G', null, 362, 'history'),
  ('product_name', 'bo loc ge pcf b04', 'GT-PCF10-G01-G', null, 363, 'history'),
  ('product_name', 'he thong loc nuoc ge wh15a', 'WH15A', null, 364, 'history'),
  ('product_name', 'phu kien đuong ong tinh them', 'PKONG', null, 365, 'history'),
  ('product_name', 'loi loc pcf may b04', 'GT-PCF10-F02G', null, 366, 'history'),
  ('product_name', 'dich vu bao tri', 'DVBT', null, 367, 'history'),
  ('product_name', 'may loc nuoc ge gn610', 'GPUN-4000XEN-G', null, 368, 'history'),
  ('product_name', 'bo loc ge nf cho may b04', 'GT-NF50-G01G', null, 369, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a eco', 'WH30AECO', null, 370, 'history'),
  ('product_name', 'may loc nuoc ge gn620', 'GTUN-5800EN-G', null, 371, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (mau đen)', 'CTS10NB', null, 372, 'history'),
  ('product_name', 'bo loc ge pcf cho may gn610', 'GT-PCF10-F02G', null, 373, 'history'),
  ('product_name', 'voi sen tam aromatherapy ge (trang)', 'GEUS-00X05', null, 374, 'history'),
  ('product_name', 'bo loc thom voi sen tam the he 2', 'VOISEN-LOITHOM', null, 375, 'history'),
  ('product_name', 'dich vu sua chua', 'DVSC', null, 376, 'history'),
  ('product_name', 'bo loc ge pcff dn810', 'LX-PPF-003-G', null, 377, 'history'),
  ('product_name', 'bo loc ge pcfb dn810', 'LX-PCFB-002-G', null, 378, 'history'),
  ('product_name', 'bo loc ge pcf cho may gn620', 'GT-PCF13-F01G', null, 379, 'history'),
  ('product_name', 'bo loc ge nf cho may gn610', 'GT-NF600-F02G', null, 380, 'history'),
  ('product_name', 'dich vu lap đat', 'DVLD', null, 381, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30a', 'WH30A', null, 382, 'history'),
  ('product_name', 'bon nuoc khang khuan palm 1500l', 'BKK1500PALM', null, 383, 'history'),
  ('product_name', 'tu inox cho ge wh30a', 'TUBAOCHE', null, 384, 'history'),
  ('product_name', 'chi phi van chuyen', 'DVVC', null, 385, 'history'),
  ('product_name', 'bo loc ge nf cho may gn620', 'GT-NF600-F01G', null, 386, 'history'),
  ('product_name', 'bo loc ge pcfb cho may ush10', 'LX-PCFB-003-G', null, 387, 'history'),
  ('product_name', 'bo loc ge cpf b04', 'GT-PCF10-G01-G', null, 388, 'history'),
  ('product_name', 'lx-cfnc-001-g', 'LX-CFNC-001-G', null, 389, 'history'),
  ('product_name', 'gt-pcf10-f02g', 'GT-PCF10-F02G', null, 390, 'history'),
  ('product_name', 'gt-nf600-f02g', 'GT-NF600-F02G', null, 391, 'history'),
  ('product_name', 'bo loc ge pcfb ush10', 'LX-PCFB-003-G', null, 392, 'history'),
  ('product_name', 'bo loc ge cfnc cts10', 'LX-CFNC-001-G', null, 393, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (đen)', 'GTUN-8600HP-G', null, 394, 'history'),
  ('product_name', 'bo loc ge nf b04', 'GT-NF50-G01G', null, 395, 'history'),
  ('product_name', 'may loc nuoc ge cts10 (trang)', 'CTS10NW', null, 396, 'history'),
  ('product_name', 'loi loc cfnc cts10', 'LX-CFNC-001-G', null, 397, 'history'),
  ('product_name', 'bo loc ge pcf gn620', 'GT-PCF13-F01G', null, 398, 'history'),
  ('product_name', 'bo loc ge nf gn620', 'GT-NF600-F01G', null, 399, 'history'),
  ('product_name', 'dich vu bao tri, sua chua may loc nuoc', 'DVBT', null, 400, 'history'),
  ('product_name', 'loi loc pp (danh cho upf10)', 'LX-PP-003-G', null, 401, 'history'),
  ('product_name', 'loi loc pac (danh cho upf10)', 'GT-PCF10-F02G', null, 402, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx: vsforgings an đo', 'MUOIAD', null, 403, 'history'),
  ('product_name', 'may loc nuoc ge gn610 (hang tang khong thu tien)', 'GPUN-4000XEN-G', null, 404, 'history'),
  ('product_name', 'chi phi di chuyen', 'DVVC', null, 405, 'history'),
  ('product_name', 'bo loc ge pcf gn610', 'GT-PCF10-F02G', null, 406, 'history'),
  ('product_name', 'dich vu lap đat pou', 'DVLD', null, 407, 'history'),
  ('product_name', '01 nam dich vu bao tri đinh ky 5 sao (3 thang/lan)', 'DVBT', null, 408, 'history'),
  ('product_name', '3 nam dich vu bao tri đinh ky 5 sao (3 thang/lan)', 'DVBT', null, 409, 'history'),
  ('product_name', 'phu kien đuong ong noi tuyen', 'PKONG', null, 410, 'history'),
  ('product_name', 'tu bao che 30a', 'TUINOX30A', null, 411, 'history'),
  ('product_name', 'bom wilo jet 4-4', 'WILOJET44', null, 412, 'history'),
  ('product_name', 'bom tang ap bien tan wilo pbi-l203ea', 'WILOPBI-L203EA', null, 413, 'history'),
  ('product_name', 'tank khang khuan wavelife 1500l (chua nuoc truoc loc)', 'BKK1500PALM', null, 414, 'history'),
  ('product_name', 'bo loc ge pcfb may ush10', 'LX-PCFB-003-G', null, 415, 'history'),
  ('product_name', 'pcf filter (use for model ge gn620)', 'GT-PCF13-F01G', null, 416, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610', 'GPUN-4000XEN-G', null, 417, 'history'),
  ('product_name', 'loi thom voi sen tam the he 2', 'VOISEN-LOITHOM', null, 418, 'history'),
  ('product_name', 'loi loc voi sen tam the he 2', 'VOISEN-LOILOC', null, 419, 'history'),
  ('product_name', 'muoi (natriclorua) tinh vissoft, dang vien, nsx:vsforings an đo', 'MUOIAD', null, 420, 'history'),
  ('product_name', 'tu bao che 30a eco', 'TUINOX30AECO', null, 421, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn620', 'GTUN-5800EN-G', null, 422, 'history'),
  ('product_name', 'may loc nuoc ge ctd50 (hang trung bay)', 'CTD50NG', null, 423, 'history'),
  ('product_name', 'vo thiet bi loc trung tam 30a', '00010073', null, 424, 'history'),
  ('product_name', 'vo thiet bi lam mem 30a', '00010076', null, 425, 'history'),
  ('product_name', 'loi loc ge pcf (gpun-4000xen-g)', 'GT-PCF10-F02G', null, 426, 'history'),
  ('product_name', 'bo loc ge nf gn610', 'GT-NF600-F02G', null, 427, 'history'),
  ('product_name', 'dich vu sua chua lap đat may loc nuoc', '_x0008_LDPOU', null, 428, 'history'),
  ('product_name', 'bo loi loc ge cpf b04', 'GT-PCF10-G01-G', null, 429, 'history'),
  ('product_name', 'muoi (natriclorua) tinh 99.9%, dang vien, nsx: đuc', 'MuoiDUC', null, 430, 'history'),
  ('product_name', 'may loc nuoc 2 trong 1 ge dn810', 'GTUN-8500XDS-G', null, 431, 'history'),
  ('product_name', 'may loc nuoc đe ban ge b04', 'GEUT-50B04-G', null, 432, 'history'),
  ('product_name', 'may loc nuoc gects20', 'CTS20NG', null, 433, 'history'),
  ('product_name', 'dich vu van chuyen', 'SHIP', null, 434, 'history'),
  ('product_name', 'may loc nuoc am tu bep ge gn610 (hang tang khong thu tien)', 'GPUN-4000XEN-G', null, 435, 'history'),
  ('product_name', 'bo loc ge pcf may gn620', 'GT-PCF13-F01G', null, 436, 'history'),
  ('product_name', 'voi sen tam aromatheraphy ge (trang)', 'GEUS-00X05', null, 437, 'history'),
  ('product_name', 'he thong loc nuoc ge wh30 eco', 'Mã hàng', null, 438, 'history'),
  ('product_name', 'dich vu bao tri đinh ky 5 sao', 'BT1Y4', null, 439, 'history'),
  ('product_name', 'may loc nuoc ge cts10 đen', 'CTS10NB', null, 440, 'history'),
  ('product_name', 'may loc nuoc đe ban ge ctd50', 'CTD50NG', null, 441, 'history'),
  ('product_name', 'may loc nuoc mini am tu bep ge gn610', 'GPUN-4000XEN-G', null, 442, 'history'),
  ('product_name', 'tank khang khuan wavelife 1500l', 'BKK1500PALM', null, 443, 'history');
